ignore build warning:
gcc  -c -MD -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-deprecated-declarations -Wno-stringop-truncation -Wno-unused-result -nostdlib -c -g -fPIC  -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/  -O2 GenVtf.c -o GenVtf.o
GenVtf.c: In function 'ConvertVersionInfo':
GenVtf.c:132:7: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
       strncpy (TemStr + 4 - Length, Str, Length);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GenVtf.c:130:14: note: length computed here
     Length = strlen(Str);
              ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [../Makefiles/footer.makefile:27: GenVtf.o] Error 1
make[4]: Leaving directory '/opt/data/development/android_build/efidroid/out/host/edk2_basetools/Source/C/GenVtf'
make[3]: *** [GNUmakefile:79: GenVtf] Error 2
make[3]: Leaving directory '/opt/data/development/android_build/efidroid/out/host/edk2_basetools/Source/C'
make[2]: *** [GNUmakefile:25: Source/C] Error 2
make[2]: Leaving directory '/opt/data/development/android_build/efidroid/out/host/edk2_basetools'
make[1]: *** [out/build.mk:1016: edk2_basetools] Error 2
make[1]: Leaving directory '/opt/data/development/android_build/efidroid'